# Generated by Django 4.1.5 on 2023-02-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_product_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='photo',
        ),
    ]
