# Generated by Django 4.1.5 on 2023-02-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
